baseurl = "http://www.stencilled.me"
languageCode = "en-us"
title = "Stencilled"
theme = "beautifulhugo"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
googleAnalytics = "UA-91161205-1"

[Params]

 # commit = false

[Author]
  name = "Senthil Thyagarajan"
  date= "2017"
  email = "senthil.thyagarajan@gmail.com"
  github = "senthilthyagarajan"
  twitter = "therascala"
  linkedin = "senthilthyagarajan"

#[[menu.main]]
#    name = "Blog"
#    url = "/"
#    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3

[[menu.main]]
parent = "projects"
name = "MTA Subway Ridership"
url = "/post/2018-08-16-MTA-Subway-Ridership"


[[menu.main]]
parent = "projects"
name = "Taps near you"
url = "/post/2017-09-18-taps-near-you"


[[menu.main]]
parent = "projects"
name = "States to Shapes"
url = "/post/2017-05-10-states-to-shapes"


[[menu.main]]
parent = "projects"
name = "Harry Potter Characters"
url = "/post/2017-05-02-Harry-Potter-Characters"


[[menu.main]]
parent = "projects"
name = "Breweries or Wineries ??"
url = "/post/2017-04-29-whats-your-states-poison"



[[menu.main]]
	parent = "projects"
	name = "Indian Premier League so far."
	url = "/post/2017-04-10-iplseasons"

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    weight = 2

[[menu.main]]
   parent = "projects"
   name = "Maps and GIFS"
   url = "/post/2017-03-20-map-gif-r"

[[menu.main]]
    parent = "projects"
    name = "NFL Season 2016-17"
    url = "/post/2017-01-29-nfl"

[[menu.main]]
    parent = "projects"
    name = "Where do people eat in Austin ?"
    url = "/post/2017-02-15-foursquare"

[[menu.main]]
	parent = "projects"
	name = "Top Beers in 2016."
	url = "/post/2017-02-22-topbeers2016"

  [[menu.main]]
  	parent = "projects"
  	name = "Airbnb Listing."
  	url = "/post/2017-10-25-airbnb-listing"






[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3
