baseurl = ""
languageCode = "en"
title = "Stencilled"
theme = "Hucore"
#copyright = "&copy; 2017 | Follow on <a href=\"https://twitter.com/therascala\" target=\"_blank\">Twitter</a> | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"
disqusShortname = "shortname"
googleAnalytics = "trackingcode"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Your description here"
keywords = ["keyword 1", "keyword 2", "keyword 3"]
author = "Morten G. Johansen"
sharingicons = true

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/mgjohansen"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/therascala"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://linkedin.com/in/senthilthyagarajan"
fa_icon = "fa-linkedin-square"

[Author]
  name = "Senthil Thyagarajan"
  date= "2020"
  email = "senthil.thyagarajan@gmail.com"
  github = "senthilthyagarajan"
  twitter = "therascala"
  linkedin = "senthil.thyagarajan"

#[[menu.main]]
#    name = "Blog"
#    url = "/"
#    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    weight = 2

[[menu.main]]
    parent = "projects"
    name = "NFL Season 2016-17"
    url = "/post/2017-01-29-nfl"

[[menu.main]]
    parent = "projects"
    name = "Where do people eat in Austin ?"
    url = "/post/2017-02-15-foursquare"

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3

