baseurl = "/"
languageCode = "en-us"
title = "Stencilled"
relativeURLs = true

[Author]
  name = "Senthil Thyagarajan"
  date= "2020"
  email = "senthil.thyagarajan@gmail.com"
  github = "senthilthyagarajan"
  twitter = "therascala"
  linkedin = "senthil.thyagarajan"

#[[menu.main]]
#    name = "Blog"
#    url = "/"
#    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    weight = 2

[[menu.main]]
    parent = "projects"
    name = "NFL Season 2016-17"
    url = "/post/2017-01-29-nfl"

[[menu.main]]
    parent = "projects"
    name = "Where do people eat in Austin ?"
    url = "/post/2017-02-15-foursquare"

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3
